#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# Dont read global configs
unsetopt GLOBAL_RCS

# Set the path to dotzsh.
export DOTZSH="$HOME/.zsh"

# Source environment settings
source "$DOTZSH/env.zsh"

# Customize to your needs...

skip_global_compinit=1

# - Exports

export ZSH=$HOME/.oh-my-zsh
export VISUAL=vim
export EDITOR="$VISUAL"
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.composer/vendor/bin:$PATH"